package com.github.forax.lazylr;

import org.jspecify.annotations.Nullable;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.MethodType;
import java.lang.invoke.WrongMethodTypeException;
import java.lang.reflect.UndeclaredThrowableException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Objects;

/// An interface for transforming a successful parse into a domain-specific
/// result, such as an Abstract Syntax Tree (AST) or an interpreted value.
///
/// The `Evaluator` maps the formal structures of the [Grammar] (terminals and
/// productions) to meaningful objects. It is invoked when the [Parser] does
/// a shift or a reduce.
///
/// ### Evaluation Flow
/// - **Leaf Nodes**: When the parser encounters a [Terminal],
///   it calls [#evaluate(Terminal)] to convert the raw token into a value
///   (e.g., parsing a string "123" into an `Integer`).
/// - **Internal Nodes**: When a [Production] is reduced, it calls
///    [#evaluate(Production, List)] with the results of its children.
///
/// ### Exception propagation
/// / Any exception thrown by either `evaluate` method stops the parse loop
/// and propagates out of [Parser#parse(java.util.Iterator, Evaluator)].
/// The parser may be reused normally with another input after an evaluator exception.
///
/// ### Creating an Evaluator
/// Implement this interface directly with a class:
/// ```java
/// class IntEvaluator implements Evaluator<Integer> {
///   public Integer evaluate(Terminal terminal) {
///     return switch (terminal.name()) {
///       case "num" -> Integer.parseInt(terminal.value());
///       default    -> 0;
///     };
///   }
///   public Integer evaluate(Production production, List<Integer> args) {
///     return switch (production.name()) {
///       case "E : num"   -> args.get(0);
///       case "E : E + E" -> args.get(0) + args.get(2);
///       default -> throw new IllegalStateException("unknown production: " + production.name());
///     };
///   }
/// }
/// ```
///
/// ### Reflective Evaluator
/// As an alternative to implementing this interface directly,
/// [#reflect(MethodHandles.Lookup, Object)] builds an `Evaluator` from the
/// methods of an arbitrary object using a lookup and reflection.
/// This lets you write plain Java methods instead of a `switch` dispatch:
///
/// ```java
/// class IntEval {
///   public int num(Terminal t) { return Integer.parseInt(t.value()); }
///
///   @ProductionName("E : E + E")
///   public int add(int left, int right) { return left + right; }
///
///   @ProductionName("E : E * E")
///   public int mul(int left, int right) { return left * right; }
/// }
///
/// var evaluator = Evaluator.reflect(MethodHandles.lookup(), new IntEval());
/// ```
///
/// [#reflect(Object)] is a convenience overload that infers the lookup from
/// the call site automatically but may be slow or fail for classes defined
/// in non-open modules.
///
/// @param <T> The type of the value produced by the evaluation.
///
/// @see Parser#parse(java.util.Iterator, Evaluator)
public interface Evaluator<T extends @Nullable Object> {
  // Design note for evaluate(Production, ...)
  // The grammar is constructed dynamically at runtime, so named accessors per
  // production, as generated by other parser libraries, are not an option here.
  // Switching on the full production name (e.g. "E: E + E") makes the body
  // explicit at the call site, so the position of each argument is self-evident.

  /// Transforms a matched [Terminal] into a value.
  ///
  /// This is typically where you extract the [Terminal#value()] (the actual
  /// lexeme from the input) and convert it into a literal or leaf node.
  ///
  /// The start position of the terminal in the input can be obtained
  /// by calling [Lexer#position(java.util.Iterator)].
  ///
  /// @param terminal The terminal token matched by the lexer.
  /// @return A value representing the terminal or `null` if the terminal has no value.
  T evaluate(Terminal terminal);

  /// Reduces a [Production] into a single value using its previously evaluated
  /// components.
  ///
  /// The `arguments` list corresponds to the [Production#body()] in order.
  /// For example, in a production `expr : expr + expr`, the list will contain:
  /// * `arguments[0]`: Result of the first `expr`.
  /// * `arguments[1]`: Result of the `+` terminal.
  /// * `arguments[2]`: Result of the second `expr`.
  ///
  /// @param production The derivation rule being reduced.
  /// @param arguments The evaluated results of each [Symbol] in the production's body.
  /// @return The result of the reduction (the new value for the production non-terminal)
  ///         or `null` if the production has no value.
  T evaluate(Production production, List<T> arguments);


  /// Creates an [Evaluator] by inspecting the methods of `object` accessible
  /// through reflection.
  ///
  /// This method can be slow or fail at runtime if the 'object' class is
  /// defined in a non-open module.
  /// You can use [#reflect(MethodHandles.Lookup, Object)] instead.
  ///
  /// The method-resolution rules are identical to those of
  /// [#reflect(MethodHandles.Lookup, Object)]:
  /// - Terminal methods are matched by name,
  /// - Production methods are matched by their [@ProductionName][ProductionName] annotation,
  /// - Single-body productions without an annotation are passed through, and
  /// - Primitive parameter/return types are transparently boxed/unboxed.
  ///
  /// @param object the object whose methods define the terminal and production
  ///               handlers; must not be `null`.
  /// @return a new `Evaluator` backed by the methods of `object`.
  /// @throws NullPointerException if `object` is `null`.
  /// @throws IllegalStateException if any inspected method violates the
  ///         constraints described in [#reflect(MethodHandles.Lookup, Object)].
  ///
  /// @see #reflect(MethodHandles.Lookup, Object)
  static Evaluator<@Nullable Object> reflect(Object object) {
    Objects.requireNonNull(object);
    final class Holder {
      private static final StackWalker WALKER =
          StackWalker.getInstance(StackWalker.Option.RETAIN_CLASS_REFERENCE);
    }
    var callerClass = Holder.WALKER.getCallerClass();
    MethodHandles.Lookup lookup;
    try {
      lookup = MethodHandles.privateLookupIn(callerClass, MethodHandles.lookup());
    } catch (IllegalAccessException e) {
      throw new IllegalStateException(e);
    }
    return reflect(lookup, object);
  }

  /// Creates an [Evaluator] by inspecting the public methods of 'object'
  /// using 'lookup' access.
  ///
  /// ### Terminal methods
  /// A public method named using the name of a [Terminal].
  /// The method return type must be non-`void`.
  /// If no method matches a given terminal name, `null` is returned
  /// for that terminal.
  ///
  /// ### Production methods
  /// A public method annotated with \@[ProductionName] whose value
  /// matches the name of a [Production].
  /// The method must have exactly one parameter for each
  /// non-`null` [Symbol] in the production body.
  ///
  /// ### Single-body pass-through
  /// If a production has exactly one symbol in its body and no
  /// `@ProductionName` method is found, the single argument
  /// is returned as-is without calling any method.
  ///
  /// Primitive parameter types are accepted; boxing and unboxing
  /// are handled transparently.
  ///
  /// ### Validation
  /// All public methods declared on `object`'s class (excluding those
  /// inherited from [Object]) are inspected when calling 'reflect()'.
  /// A method is rejected immediately with [IllegalStateException] if:
  /// - It has no parameters,
  /// - Its return type is `void`,
  /// - It has a single parameter that is not [Terminal] and carries no
  ///   \@[ProductionName] annotation.
  ///
  /// @param lookup the lookup to use when creating method handles; its access
  ///               rights determine which methods on `object` are reachable.
  ///               Must not be `null`.
  /// @param object the object whose public methods define the terminal and
  ///               production handlers; must not be `null`.
  /// @return a new 'Evaluator' backed by the methods of 'object'.
  /// @throws NullPointerException if 'lookup' or 'object' is `null`.
  /// @throws IllegalStateException if any public method on 'object' violates
  ///         the constraints above, or if the lookup does not have enough
  ///         access to unreflect a public method.
  static Evaluator<@Nullable Object> reflect(MethodHandles.Lookup lookup, Object object) {
    Objects.requireNonNull(lookup);
    Objects.requireNonNull(object);
    var methods = object.getClass().getMethods();
    var productionMap = new HashMap<String, MethodHandle>();
    var terminalMap = new HashMap<String, MethodHandle>();
    for(var method : methods) {
      if (method.getDeclaringClass() == Object.class) {
        continue;
      }
      if (method.getParameterCount() == 0) {
        throw new IllegalStateException("method " + method + " has no arguments");
      }
      if (method.getReturnType() == void.class) {
        throw new IllegalStateException("method " + method + " has no return type");
      }
      MethodHandle mh;
      try {
        mh = lookup.unreflect(method);
      } catch (IllegalAccessException e) {
        throw new IllegalStateException(e);
      }
      var productionName = method.getAnnotation(ProductionName.class);
      if (productionName != null) {
        productionMap.put(productionName.value(),
            mh.asSpreader(Object[].class, method.getParameterCount())
                .asType(MethodType.methodType(Object.class, Object.class, Object[].class)));
        continue;
      }
      if (method.getParameterCount() != 1 || method.getParameterTypes()[0] != Terminal.class) {
        throw new IllegalStateException("terminal method " + method + " should take a single Terminal argument");
      }
      terminalMap.put(method.getName(),
          mh.asType(MethodType.methodType(Object.class, Object.class,Terminal.class)));
    }
    return new Evaluator<@Nullable Object>() {
      @Override
      public @Nullable Object evaluate(Terminal terminal) {
        var mh = terminalMap.get(terminal.name());
        if (mh == null) {
          return null;  // The Terminal has no value
        }
        try {
          return mh.invokeExact(object, terminal);
        } catch(WrongMethodTypeException | ClassCastException e) {
          throw new IllegalStateException("terminal method " + terminal.name() + " has wrong parameter type", e);
        } catch (RuntimeException | Error e) {
          throw e;
        } catch (Throwable e) {
          throw new UndeclaredThrowableException(e);
        }
      }

      @Override
      public @Nullable Object evaluate(Production production, List<@Nullable Object> arguments) {
        var mh = productionMap.get(production.name());
        if (mh == null) {
          // A production can have no evaluator if it is a leaf node
          if (production.body().size() == 1) {
            return arguments.getFirst();
          }
          throw new IllegalStateException("production " + production.name() + " has no evaluator");
        }
        var values = arguments.stream()
            .filter(Objects::nonNull)
            .toArray();
        try {
          return mh.invokeExact(object, values);
        } catch(WrongMethodTypeException | ClassCastException e) {
          throw new IllegalStateException("production method " + production.name() +
              " has wrong parameter types, arguments " + Arrays.toString(values), e);
        } catch (RuntimeException | Error e) {
          throw e;
        } catch (Throwable e) {
          throw new UndeclaredThrowableException(e);
        }
      }
    };
  }
}