on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: GraalVM 25
    steps:
      - uses: actions/checkout@v6
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '25'
          cache: maven

      - name: Get VERSION from tag or commit
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          fi

      - name: build
        run: |
          mvn -B package -Pnative
          cp target/lazylr-*.jar lazylr-${{ env.VERSION }}.jar
          cp target/lazylr lazylr-linux-${{ env.VERSION }}

      - name: Upload Java Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lazylr-java
          path: lazylr-*.jar
          overwrite: true

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lazylr-linux
          path: lazylr-linux-*
          overwrite: true

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            lazylr-java/*
            lazylr-linux/*
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true